### ISSUE TITLE
https://downloads.makerbot.com/makerware/ubuntu ACCESS DENIED

### ISSUE THREAD

**Issue by mherweg** [lanceseidman/makerware#1]
:-(

> 
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2FD1C9F8DE022C16</RequestId><HostId>9J21l4AqEB7f0dgIfI+6gWxlc03v9mODfCZnD4FgslPk+4wtXFHvtKlMgWYuKbSAjTUltmXQ0Qc=</HostId></Error>

**Comment by lanceseidman** [comment]
Sadly looks like they're not providing access to it anymore.
